### ISSUE TITLE
"Indent" config option seems to be ignored

### ISSUE THREAD

**Issue by nsforge** [paulrobertlloyd/jekyll-pypedown#3]
I've tried a bunch of different combinations in my `_config.yml`, but I can't seem to get the `indent` option to work. This is what I'm using to configure Pypedown:

``` yaml
markdown: Pypedown

pypedown:
  input: GFM
  indent: 1

gems:
  - jekyll-pypedown
```

The output I'm getting has 8 spaces per tab, no matter what I set for `indent`. Am I configuring it incorrectly?
